apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.106.108.15
  environments:
  - key: dev
    owner: dubeyhari76
    repository: jenkinsx-k8s
  - key: staging
  - key: production
  ingress:
    domain: 172.17.0.2.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: dubeyhari76
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
